artifact_location: /Users/fazlikoc/Desktop/Projects/multimodal-ai-agent/project4_finetuning_lab/runs/mlflow/0
creation_time: 1772064081910
experiment_id: '0'
last_update_time: 1772064081910
lifecycle_stage: active
name: Default
workspace: default
