artifact_location: /Users/fazlikoc/Desktop/Projects/multimodal-ai-agent/project4_finetuning_lab/runs/mlflow/530644761755783905
creation_time: 1772064081913
experiment_id: '530644761755783905'
last_update_time: 1772064081913
lifecycle_stage: active
name: output
workspace: default
